sudo: false

language: android

android:
  components:
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

notifications:
  email: false
