sudo: false

language: android

android:
  components:
    - build-tools-21.1.1
    - android-21
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

notifications:
  email: false
